In [1]:
import numpy as np
import pandas as pd

In [6]:
# filename = "grid_50_obs_30.csv"
# filename = "grid_32.csv"
# filename = "grid_16.csv"
# filename = "maze_32.csv"
# filename = "grid_20_obs_30.csv"

data = pd.read_csv(filename, index_col=0)
data = data.set_index("name")
data

,3,5,10,SMT-CBS,DYN 8_2,DYN 10_3
name,,,,,,
grid_32x32_a2,0.035660,0.042392,0.048132,0.037228,0.044675,0.058352
grid_32x32_a4,0.665633,0.677483,0.786683,0.663800,0.661017,0.776283
grid_32x32_a6,1.057683,0.852083,1.229000,0.880217,0.971400,0.985900
grid_32x32_a8,1.233333,1.079833,1.587167,1.150667,1.251000,1.219500
grid_32x32_a10,1.002317,0.839633,1.161667,0.889517,0.971767,0.969500
grid_32x32_a12,1.942167,2.215167,2.440333,1.773833,1.921667,1.887167
grid_32x32_a14,1.353333,1.526833,1.858667,1.265833,1.480500,1.423000
grid_32x32_a16,8.577667,9.339500,9.766333,8.103333,8.008000,7.809333
grid_32x32_a18,4.915167,4.812667,5.872667,4.352833,4.720333,4.618500
grid_32x32_a20,5.711000,5.398833,7.183500,5.596000,5.737500,5.713833
grid_32x32_a22,11.188333,11.616667,13.176667,11.158333,10.811667,10.700167
grid_32x32_a24,17.191667,15.135000,22.775000,18.530000,15.320000,15.741667
grid_32x32_a26,5.456667,5.460500,7.129500,5.956833,5.694500,5.676000
grid_32x32_a28,6.807167,6.654833,9.675333,7.316000,7.354500,7.109833
grid_32x32_a30,9.408000,10.265500,14.191667,10.578333,10.152667,9.819667

In [9]:
# Sum of percentage improvement. Minus means deterioration.
df = data.copy()
for n in ["3", "5", "10", "DYN 8_2", "DYN 10_3"]:
    df[n] = df["SMT-CBS"] - df[n]
df.loc["Total"] = df.sum()
df

                       3         5         10    SMT-CBS   DYN 8_2  DYN 10_3
name
grid_32x32_a2   0.001568 -0.005163  -0.010903   0.037228 -0.007447 -0.021123
grid_32x32_a4  -0.001833 -0.013683  -0.122883   0.663800  0.002783 -0.112483
grid_32x32_a6  -0.177467  0.028133  -0.348783   0.880217 -0.091183 -0.105683
grid_32x32_a8  -0.082667  0.070833  -0.436500   1.150667 -0.100333 -0.068833
grid_32x32_a10 -0.112800  0.049883  -0.272150   0.889517 -0.082250 -0.079983
grid_32x32_a12 -0.168333 -0.441333  -0.666500   1.773833 -0.147833 -0.113333
grid_32x32_a14 -0.087500 -0.261000  -0.592833   1.265833 -0.214667 -0.157167
grid_32x32_a16 -0.474333 -1.236167  -1.663000   8.103333  0.095333  0.294000
grid_32x32_a18 -0.562333 -0.459833  -1.519833   4.352833 -0.367500 -0.265667
grid_32x32_a20 -0.115000  0.197167  -1.587500   5.596000 -0.141500 -0.117833
grid_32x32_a22 -0.030000 -0.458333  -2.018333  11.158333  0.346667  0.458167
grid_32x32_a24  1.338333  3.395000  -4.245000  18.530000  3.210000  2.788333
grid_32x32_a26  0.500167  0.496333  -1.172667   5.956833  0.262333  0.280833
grid_32x32_a28  0.508833  0.661167  -2.359333   7.316000 -0.038500  0.206167
grid_32x32_a30  1.170333  0.312833  -3.613333  10.578333  0.425667  0.758667
Total           1.706968  2.335837 -20.629553  78.252762  3.151570  3.744060

In [10]:
df.to_csv(f"sub/{filename}")

In [37]:
# ([(1-data[i] / data["SMT-CBS"]) for i in ["3", "5", "10", "DYN 8_2", "DYN 10_3"]])

In [ ]:
## Merging DYN

In [2]:
def load_output(filename, n):
    p = list(range(6))
    p.insert(0, "name")
    data = pd.read_csv(filename, names=p)
    data[n] = data.mean(numeric_only=True, axis=1)
    data = data.drop(list(range(6)), axis=1)
    return data

In [3]:
data2 = load_output("../code/output/dpll_mapf_8_2.csv", "DYN_8_2")
data3 = load_output("../code/output/dpll_mapf_10_3.csv", "DYN_10_3")
data2

              name    DYN_8_2
0    grid_32x32_a2   0.044675
1    grid_32x32_a4   0.661017
2    grid_32x32_a6   0.971400
3    grid_32x32_a8   1.251000
4   grid_32x32_a10   0.971767
5   grid_32x32_a12   1.921667
6   grid_32x32_a14   1.480500
7   grid_32x32_a16   8.008000
8   grid_32x32_a18   4.720333
9   grid_32x32_a20   5.737500
10  grid_32x32_a22  10.811667
11  grid_32x32_a24  15.320000
12  grid_32x32_a26   5.694500
13  grid_32x32_a28   7.354500
14  grid_32x32_a30  10.152667

In [5]:
data = pd.merge(data,data2,on=["name"])
data = pd.merge(data,data3,on=["name"])
data

,name,average 3,average 5,average 10,average SMT-CBS,DYN_8_2,DYN_10_3
0,grid_32x32_a2,0.035660,0.042392,0.048132,0.037228,0.044675,0.058352
1,grid_32x32_a4,0.665633,0.677483,0.786683,0.663800,0.661017,0.776283
2,grid_32x32_a6,1.057683,0.852083,1.229000,0.880217,0.971400,0.985900
3,grid_32x32_a8,1.233333,1.079833,1.587167,1.150667,1.251000,1.219500
4,grid_32x32_a10,1.002317,0.839633,1.161667,0.889517,0.971767,0.969500
5,grid_32x32_a12,1.942167,2.215167,2.440333,1.773833,1.921667,1.887167
6,grid_32x32_a14,1.353333,1.526833,1.858667,1.265833,1.480500,1.423000
7,grid_32x32_a16,8.577667,9.339500,9.766333,8.103333,8.008000,7.809333
8,grid_32x32_a18,4.915167,4.812667,5.872667,4.352833,4.720333,4.618500
9,grid_32x32_a20,5.711000,5.398833,7.183500,5.596000,5.737500,5.713833
10,grid_32x32_a22,11.188333,11.616667,13.176667,11.158333,10.811667,10.700167
11,grid_32x32_a24,17.191667,15.135000,22.775000,18.530000,15.320000,15.741667
12,grid_32x32_a26,5.456667,5.460500,7.129500,5.956833,5.694500,5.676000
13,grid_32x32_a28,6.807167,6.654833,9.675333,7.316000,7.354500,7.109833
14,grid_32x32_a30,9.408000,10.265500,14.191667,10.578333,10.152667,9.819667

In [6]:
# data.to_csv(filename)