In [1]:
import numpy as np
import pandas as pd

In [34]:
# filename = "grid_50_obs_30.csv"
# filename = "grid_32.csv"
# filename = "grid_16.csv"
# filename = "maze_32.csv"
filename = "grid_20_obs_30.csv"

data = pd.read_csv(filename, index_col=0)
data = data.set_index("name")
data

                       3         5        10   DYN 8_2  DYN 10_3   SMT-CBS
name
grid_20x20_a2   0.028100  0.028510  0.028537  0.030790  0.030273  0.027515
grid_20x20_a4   0.026975  0.027038  0.027080  0.035100  0.031935  0.027477
grid_20x20_a6   0.047245  0.046093  0.045885  0.063237  0.054125  0.047028
grid_20x20_a8   0.100897  0.100590  0.100733  0.129133  0.109933  0.106827
grid_20x20_a10  0.060343  0.056953  0.058063  0.067075  0.062258  0.068378
grid_20x20_a12  0.199417  0.204467  0.201883  0.263267  0.205517  0.215050
grid_20x20_a14  0.245517  0.245650  0.246200  0.236333  0.258317  0.221250
grid_20x20_a16  0.279683  0.280317  0.278617  0.332550  0.303817  0.322633
grid_20x20_a18  0.174800  0.175217  0.174517  0.244533  0.210267  0.237733
grid_20x20_a20  0.203150  0.202233  0.203250  0.269333  0.222750  0.254467
grid_20x20_a22  0.660867  0.663417  0.660433  0.617633  0.479900  0.594933
grid_20x20_a24  0.975533  0.974033  0.974250  1.097167  1.009500  1.110817
grid_20x20_a26  1.607500  1.609500  1.604167  0.747033  0.819817  1.386000
grid_20x20_a28  0.868133  0.866350  0.867483  0.705167  1.013667  0.865117
grid_20x20_a30  2.177167  2.177333  2.173000  1.608000  2.085667  1.232500

In [35]:
# Sum of percentage improvement. Minus means deterioration.
df = data.copy()
for n in ["3", "5", "10", "DYN 8_2", "DYN 10_3"]:
    df[n] = df["SMT-CBS"] - df[n]
df

                       3         5        10   DYN 8_2  DYN 10_3   SMT-CBS
name
grid_20x20_a2  -0.000585 -0.000995 -0.001022 -0.003275 -0.002758  0.027515
grid_20x20_a4   0.000502  0.000438  0.000397 -0.007623 -0.004458  0.027477
grid_20x20_a6  -0.000217  0.000935  0.001143 -0.016208 -0.007097  0.047028
grid_20x20_a8   0.005930  0.006237  0.006093 -0.022307 -0.003107  0.106827
grid_20x20_a10  0.008035  0.011425  0.010315  0.001303  0.006120  0.068378
grid_20x20_a12  0.015633  0.010583  0.013167 -0.048217  0.009533  0.215050
grid_20x20_a14 -0.024267 -0.024400 -0.024950 -0.015083 -0.037067  0.221250
grid_20x20_a16  0.042950  0.042317  0.044017 -0.009917  0.018817  0.322633
grid_20x20_a18  0.062933  0.062517  0.063217 -0.006800  0.027467  0.237733
grid_20x20_a20  0.051317  0.052233  0.051217 -0.014867  0.031717  0.254467
grid_20x20_a22 -0.065933 -0.068483 -0.065500 -0.022700  0.115033  0.594933
grid_20x20_a24  0.135283  0.136783  0.136567  0.013650  0.101317  1.110817
grid_20x20_a26 -0.221500 -0.223500 -0.218167  0.638967  0.566183  1.386000
grid_20x20_a28 -0.003017 -0.001233 -0.002367  0.159950 -0.148550  0.865117
grid_20x20_a30 -0.944667 -0.944833 -0.940500 -0.375500 -0.853167  1.232500

In [36]:
df.loc["Total"] = df.sum()
df

                       3         5        10   DYN 8_2  DYN 10_3   SMT-CBS
name
grid_20x20_a2  -0.000585 -0.000995 -0.001022 -0.003275 -0.002758  0.027515
grid_20x20_a4   0.000502  0.000438  0.000397 -0.007623 -0.004458  0.027477
grid_20x20_a6  -0.000217  0.000935  0.001143 -0.016208 -0.007097  0.047028
grid_20x20_a8   0.005930  0.006237  0.006093 -0.022307 -0.003107  0.106827
grid_20x20_a10  0.008035  0.011425  0.010315  0.001303  0.006120  0.068378
grid_20x20_a12  0.015633  0.010583  0.013167 -0.048217  0.009533  0.215050
grid_20x20_a14 -0.024267 -0.024400 -0.024950 -0.015083 -0.037067  0.221250
grid_20x20_a16  0.042950  0.042317  0.044017 -0.009917  0.018817  0.322633
grid_20x20_a18  0.062933  0.062517  0.063217 -0.006800  0.027467  0.237733
grid_20x20_a20  0.051317  0.052233  0.051217 -0.014867  0.031717  0.254467
grid_20x20_a22 -0.065933 -0.068483 -0.065500 -0.022700  0.115033  0.594933
grid_20x20_a24  0.135283  0.136783  0.136567  0.013650  0.101317  1.110817
grid_20x20_a26 -0.221500 -0.223500 -0.218167  0.638967  0.566183  1.386000
grid_20x20_a28 -0.003017 -0.001233 -0.002367  0.159950 -0.148550  0.865117
grid_20x20_a30 -0.944667 -0.944833 -0.940500 -0.375500 -0.853167  1.232500
Total          -0.937602 -0.939977 -0.926373  0.271373 -0.180017  6.717725

In [40]:
df.to_csv(f"sub/{filename}")

In [37]:
# ([(1-data[i] / data["SMT-CBS"]) for i in ["3", "5", "10", "DYN 8_2", "DYN 10_3"]])

In [ ]:
## Merging DYN

In [2]:
def load_output(filename, n):
    p = list(range(6))
    p.insert(0, "name")
    data = pd.read_csv(filename, names=p)
    data[n] = data.mean(numeric_only=True, axis=1)
    data = data.drop(list(range(6)), axis=1)
    return data

In [3]:
data2 = load_output("../code/output/dpll_mapf_8_2.csv", "DYN_8_2")
data3 = load_output("../code/output/dpll_mapf_10_3.csv", "DYN_10_3")
data2

              name    DYN_8_2
0    grid_32x32_a2   0.044675
1    grid_32x32_a4   0.661017
2    grid_32x32_a6   0.971400
3    grid_32x32_a8   1.251000
4   grid_32x32_a10   0.971767
5   grid_32x32_a12   1.921667
6   grid_32x32_a14   1.480500
7   grid_32x32_a16   8.008000
8   grid_32x32_a18   4.720333
9   grid_32x32_a20   5.737500
10  grid_32x32_a22  10.811667
11  grid_32x32_a24  15.320000
12  grid_32x32_a26   5.694500
13  grid_32x32_a28   7.354500
14  grid_32x32_a30  10.152667

In [5]:
data = pd.merge(data,data2,on=["name"])
data = pd.merge(data,data3,on=["name"])
data

,name,average 3,average 5,average 10,average SMT-CBS,DYN_8_2,DYN_10_3
0,grid_32x32_a2,0.035660,0.042392,0.048132,0.037228,0.044675,0.058352
1,grid_32x32_a4,0.665633,0.677483,0.786683,0.663800,0.661017,0.776283
2,grid_32x32_a6,1.057683,0.852083,1.229000,0.880217,0.971400,0.985900
3,grid_32x32_a8,1.233333,1.079833,1.587167,1.150667,1.251000,1.219500
4,grid_32x32_a10,1.002317,0.839633,1.161667,0.889517,0.971767,0.969500
5,grid_32x32_a12,1.942167,2.215167,2.440333,1.773833,1.921667,1.887167
6,grid_32x32_a14,1.353333,1.526833,1.858667,1.265833,1.480500,1.423000
7,grid_32x32_a16,8.577667,9.339500,9.766333,8.103333,8.008000,7.809333
8,grid_32x32_a18,4.915167,4.812667,5.872667,4.352833,4.720333,4.618500
9,grid_32x32_a20,5.711000,5.398833,7.183500,5.596000,5.737500,5.713833
10,grid_32x32_a22,11.188333,11.616667,13.176667,11.158333,10.811667,10.700167
11,grid_32x32_a24,17.191667,15.135000,22.775000,18.530000,15.320000,15.741667
12,grid_32x32_a26,5.456667,5.460500,7.129500,5.956833,5.694500,5.676000
13,grid_32x32_a28,6.807167,6.654833,9.675333,7.316000,7.354500,7.109833
14,grid_32x32_a30,9.408000,10.265500,14.191667,10.578333,10.152667,9.819667

In [6]:
# data.to_csv(filename)